# Development override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  # Backend in development mode
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder  # Use development stage
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    volumes:
      - ./backend/src:/app/src
      - ./backend/logs:/app/logs
    command: npm run dev

  # Frontend in development mode
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_URL=/api
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    command: npm run dev

  # Nginx with development configuration
  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf:ro

  # Add development database with exposed port
  postgres:
    ports:
      - "5432:5432"

  # Add development redis with exposed port
  redis:
    ports:
      - "6379:6379"
